#!/system/bin/sh
X="/data/user/0/com.ownhere.ro/files/X"
vmos1D="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot01/sdcard/Download"
vmos1="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot01/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
vmos2="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot02/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
vmos3="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot03/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
vmos4="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot04/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
vmos5="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot05/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
vmos6="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot06/sdcard/Android/data/cjadao.ibbhip.ibjhfq.gcfcjr/files/HotUpdate"
#chmod -R 777 $YB
cp -p -R $X/curl /system/bin/curl
chmod -R 777 /system/bin/curl
curl --ssl-no-revoke -k https://raw.gitmirror.com/ownherePlus/ro/main/app/src/main/assets/D/890358105.robytes -O /
curl --ssl-no-revoke -k https://raw.gitmirror.com/ownherePlus/ro/main/app/src/main/assets/D/_file_list_2.23.1.81 -O /
cp -p -R $X/890358105.robytes $vmos1D/
cp -p -R $X/_file_list_2.23.1.81 $vmos1D/
cp -p -R $vmos1D/890358105.robytes $vmos1D/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos1D/
cp -p -R $vmos1D/890358105.robytes $vmos1/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos1/
cp -p -R $vmos1D/890358105.robytes $vmos2/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos2/
cp -p -R $vmos1D/890358105.robytes $vmos3/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos3/
cp -p -R $vmos1D/890358105.robytes $vmos4/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos4/
cp -p -R $vmos1D/890358105.robytes $vmos5/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos5/
cp -p -R $vmos1D/890358105.robytes $vmos6/
cp -p -R $vmos1D/_file_list_2.23.1.81 $vmos6/



