#!/system/bin/sh
X="/data/user/0/com.ownhere.ro/files/X"
cp -p -R $X/curl /system/bin/curl
chmod -R 777 /system/bin/curl
rm -rf $X/qq.apk
curl --ssl-no-revoke -k https://raw.gitmirror.com/ownherePlus/ro/main/app/src/main/assets/A/qq  -O /
mv qq qq.apk
pm install -r $X/qq.apk

