#!/system/bin/sh
YB="/storage/emulated/0/xsp"
vmos1="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot01/sdcard"
vmos2="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot02/sdcard"
vmos3="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot03/sdcard"
vmos4="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot04/sdcard"
vmos5="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot05/sdcard"
vmos6="/data/user/0/com.miHoYo.GenshinImpact/osimg/r/ot06/sdcard"
#chmod -R 777 $YB
rm -rf $vmos1/xsp/*
rm -rf $vmos2/xsp/*
rm -rf $vmos3/xsp/*
rm -rf $vmos4/xsp/*
rm -rf $vmos5/xsp/*
rm -rf $vmos6/xsp/*
cp -p -R $YB/* $vmos1/xsp/
cp -p -R $YB/* $vmos2/xsp/
cp -p -R $YB/* $vmos3/xsp/
cp -p -R $YB/* $vmos4/xsp/
cp -p -R $YB/* $vmos5/xsp/
cp -p -R $YB/* $vmos6/xsp/
chmod -R 777 $vmos1/xsp
chmod -R 777 $vmos2/xsp
chmod -R 777 $vmos3/xsp
chmod -R 777 $vmos4/xsp
chmod -R 777 $vmos5/xsp
chmod -R 777 $vmos6/xsp


